### PR TITLE
Swift Package

### PR DESCRIPTION
**Pull request by tonyarnold**
I'm not sure if this project is still being actively used, but I was keen to see if it met my needs - as part of that, I have: 

- Converted the project to be a Swift package
- Setup a GitHub Actions workflow to test the package

### CODE REVIEW

**Comment by insidegui** [comment]
Thanks a bunch @tonyarnold 

I had done this in a separate branch ([relevant commit](https://github.com/insidegui/CloudKitCodable/commit/0aed3041c4d03c07280fb6f47fabd943a337a43a)), but I believe your implementation is much more complete than what I had done.

I'm currently quite busy preparing app updates for macOS 13, so I won't be able to do much testing on my end here, but I'm happy to merge this as soon as you think it's ready.

**Comment by tonyarnold** [comment]
That's great to hear, @insidegui. 

Did you want me to restore the Xcode project so that people who are still using can continue to? Or do you feel we've crossed the point where SwiftPM is enough? (I think we're there, but it's your project).

**Comment by insidegui** [comment]
I agree, I think we can keep it as just a SPM package.

**Review by insidegui — APPROVED** [review]

**Comment by tonyarnold** [comment]
Okay, I'm happy with this - I expect there may be a couple of tweaks required for GitHub Actions, but let's deal with those once this change is merged in.

**Pull request merged**
